### ISSUE TITLE
segv with paren

### ISSUE THREAD

**Issue by zneel** [zneel/minishell#65]
```
➜  minishell git:(main) ✗ ./minishell
minishell> ()
AddressSanitizer:DEADLYSIGNAL
=================================================================
==4896==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55d1fb6146dc bp 0x7ffc3c863e40 sp 0x7ffc3c863cc0 T0)
==4896==The signal is caused by a READ memory access.
==4896==Hint: address points to the zero page.
    #0 0x55d1fb6146dc in expand_tree /home/ebouvier/42/minishell/src/expand/expand.c:82:3
    #1 0x55d1fb60f349 in execute /home/ebouvier/42/minishell/src/main.c:40:2
    #2 0x55d1fb60f736 in main /home/ebouvier/42/minishell/src/main.c:93:4
    #3 0x7fdf907a2d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #4 0x7fdf907a2e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #5 0x55d1fb551404 in _start (/home/ebouvier/42/minishell/minishell+0x22404) (BuildId: 3e4fda86b3b35e514a5539cbd90000bd154b6fe2)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/ebouvier/42/minishell/src/expand/expand.c:82:3 in expand_tree
==4896==ABORTING
```

**Comment by zneel** [comment]
fixed
