### ISSUE TITLE
segv 

### ISSUE THREAD

**Issue by zneel** [zneel/minishell#68]
```
minishell> |
AddressSanitizer:DEADLYSIGNAL
=================================================================
==11475==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x5617c49006dc bp 0x7fffab0e6290 sp 0x7fffab0e6120 T0)
==11475==The signal is caused by a READ memory access.
==11475==Hint: address points to the zero page.
    #0 0x5617c49006dc in expand_tree /home/ebouvier/42/minishell/src/expand/expand.c:82:3
    #1 0x5617c4900613 in expand_tree /home/ebouvier/42/minishell/src/expand/expand.c:79:2
```

**Comment by zneel** [comment]
not segfaulting but no syntax error
